---
  - name: Output
    debug: msg="[echo] Use 'standard' entrypoint."
    when: not has_custom_command

  - name: create client container {{ container_name }} without custom command
    docker:
      docker_api_version: 1.17
      image: "{{ image }}"
      name: "{{ container_name }}"
      detach: False
      expose: "{{ ports }}"
      ports: "{{ ports }}"
      volumes: "{{ volumes }}"
      state: running
    register: dockerout
    when: not has_custom_command

  # - debug: vars=dockerout msg="{{ dockerout }}"
  #   when: not has_custom_command

  - fail: msg="[echo] Container '{{ container_name }}' is {{ dockerout.invocation.module_complex_args.state }}"
    when: not has_custom_command and dockerout.invocation.module_complex_args.state != "running"

  - name: Output
    debug: msg="[echo] Use '{{ command }}' with entrypoint."
    when: has_custom_command

  - name: create client container {{ container_name }} with custom command
    docker:
      docker_api_version: 1.17
      image: "{{ image }}"
      name: "{{ container_name }}"
      detach: False
      expose: "{{ ports }}"
      ports: "{{ ports }}"
      volumes: "{{ volumes }}"
      command: "{{ command }}"
      state: running
    register: dockerout
    when: has_custom_command

  # - debug: vars=dockerout msg="{{ dockerout }}"
  #   when: has_custom_command

  - fail: msg="[echo] Container '{{ container_name }}' is {{ dockerout.invocation.module_complex_args.state }}"
    when: has_custom_command and dockerout.invocation.module_complex_args.state != "running"
