---
- name: CHECK VARS | Check variables
  fail: msg="[error] {{ item }} is not defined"
  when: "{{ item }} is not defined"
  with_items:
    - image
    - env_name
    - site_name


    # - name: SETUP | Create "{{ env_name }}.{{ site_name }}" entry in inventory
    #   local_action: lineinfile
    #       dest="{{ global_inventory }}"
    #       line="{{ env_name }}.{{ site_name }} ansible_ssh_host=ip"
    #       regexp="^{{ env_name }}.{{ site_name }} ansible_ssh_host="
    #       insertafter="EOF"
    #       state=present
