---
- name: INSTALL | Check 'hostname' and 'uname'
  shell: hostname -f && uname -a    
  register: checkout
  remote_user: root
  delegate_to: '{{ container_name }}'
  when: do_debug|bool
- debug: msg='INSTALL | {{ checkout }}'
  when: do_debug|bool

- name: INSTALL | Installing nginx
  apt:
    name: nginx
    state: latest
    update_cache: no 
  remote_user: root
  delegate_to: '{{ container_name }}'
  tags: nginx

- name: INSTALL | Stopping NGINX
  service:
    name: nginx
    state: stopped
  remote_user: root
  delegate_to: '{{ container_name }}'
  tags: nginx

- debug: msg='INSTALL | Copy {{ files_base }}default {{ site_default_path }}/default'
  when: do_debug|bool
- name: INSTALL | Prepare special nginx config
  copy: src='{{ files_base }}default' dest='{{ site_default_path }}/default' mode=644
  remote_user: root
  delegate_to: '{{ container_name }}'
  register: checkout
  failed_when: checkout.state != 'file'
  tags: nginx
- debug: msg='INSTALL | {{ checkout }}'
  when: do_debug|bool and checkout is defined

- debug: msg='INSTALL | {{ templates_base }}{{ item }} {{ volume_home }}/{{ item }}'
  with_items:
    - index.html
    - offline.html
  when: do_debug|bool
- name: INSTALL | Prepare special '{{ item }}'
  template: src='{{ templates_base }}{{ item }}' dest='{{ volume_home }}/{{ item }}' mode=644
  register: checkout
  with_items:
    - index.html
    - offline.html
  failed_when: checkout.state != 'file'
  tags: nginx
- debug: msg='INSTALL | {{ checkout }}'
  when: do_debug|bool and checkout is defined

- name: INSTALL | Starting NGINX
  service:
    name: nginx
    state: started
  remote_user: root
  delegate_to: '{{ container_name }}'
  tags: nginx

- name: INSTALL | Wait for NGINX to start
  wait_for: port=80
  remote_user: root
  delegate_to: '{{ container_name }}'
  tags: nginx
     
- debug: msg='INSTALL | {{ inventory_hostname }}'
  when: do_debug|bool and inventory_hostname is defined
- debug: msg='INSTALL | {{ container_ip }}'
  when: do_debug|bool and container_ip is defined
- name: INSTALL | Check
  local_action: uri url=http://{{ container_ip }}
  register: checkout
  failed_when: checkout.status != 200
  remote_user: root
  delegate_to: '{{ container_name }}'
  tags: nginx
- debug: msg='INSTALL | {{ checkout.status }}'
  when: do_debug|bool and checkout is defined

- name: INSTALL | Check offline.html
  local_action: uri url='http://{{ container_ip }}/offline.html'
  register: checkout
  failed_when: checkout.status != 200
  remote_user: root
  delegate_to: '{{ container_name }}'
  tags: nginx
- debug: msg='INSTALL | {{ checkout.status }}'
  when: do_debug|bool and checkout is defined

# - name: INSTALL | Stopping NGINX
#   service:
#     name: nginx
#     state: stopped
#   remote_user: root
#   delegate_to: '{{ container_name }}'
#   tags: nginx
