---
- debug: msg="[Debug] SETUP | {{ templates_base }}{{ item }} {{ volume_home }}/{{ item }}"
  with_items:
    - index.html
    - offline.html
  when: do_debug|bool
- name: SETUP | Prepare special "{{ item }}"
  template: src="{{ templates_base }}{{ item }}" dest="{{ volume_home }}/{{ item }}" mode=644
  register: checkout
  with_items:
    - index.html
    - offline.html
  failed_when: checkout.state != "file"
  tags: nginx
- debug: msg="[Debug] SETUP | {{ checkout }}"
  when: do_debug|bool and checkout is defined
