---
- name: SITE | Boot website
  hosts: dockerhost
  gather_facts: no
  sudo: no

  vars:
    - do_debug: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ../..

  vars_files:
    - "{{ base_folder }}/roles/common/vars/defaults.yml"
    - "{{ base_folder }}/roles/site/vars/defaults.yml"

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

  tasks:
    - name: CHECK | Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
      register: checkout
      failed_when: checkout.rc != 0
    - debug: msg="{{ checkout }}"
      when: do_debug|bool

    - debug: msg="[Debug] {{ container_name }}"
      when: do_debug|bool and container_name is defined

    - name: BOOT | Start docker container
      include: '{{ common_tasks_base }}start.yml'

    - name: BOOT | Get docker container information
      include: '{{ common_tasks_base }}get_facts.yml'

    - name: BOOT | Add docker container to inventory
      include: '{{ common_tasks_base }}add_host.yml'

    - name: BOOT | Install nginx
      include: '{{ tasks_base }}install.yml'
