---
- name: DEPLOY | Prepares and deploys a working websites
  hosts: dockerhost
  gather_facts: no
  sudo: no

  vars:
    - do_debug: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ../..
    - version: 0.1.6

  vars_files:
    - "{{ base_folder }}/roles/common/vars/defaults.yml"
    - "{{ base_folder }}/roles/site/vars/defaults.yml"

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

  tasks:
    - name: DEPLOY | Check variables
      include: '{{ tasks_base }}check_vars.yml'

    - name: DEPLOY | Get docker container information
      include: "{{ common_tasks_base }}get_facts.yml"

    - name: DEPLOY | Add docker container to inventory
      include: "{{ common_tasks_base }}add_host.yml"

    - name: DEPLOY | Deploy files
      include: '{{ tasks_base }}deploy.yml'
