---
- name: START | Start a running website '{{ container_name }}' container based on '{{ image }}'
  hosts: dockerhost
  gather_facts: no
  become: no

  vars:
    - do_debug: False
    - do_check_docker: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ../..

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'
    - '{{ base_folder }}/roles/{{ image }}/vars/defaults.yml'

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

    - include: '{{ common_tasks_base }}check_docker.yml'
      when: do_check_docker|bool

  tasks:
    - name: START | Start docker container
      include: '{{ common_tasks_base }}start.yml'

    - name: START | Get docker container information
      include: '{{ common_tasks_base }}get_facts.yml'

    - name: START | Add docker container to inventory
      include: '{{ common_tasks_base }}add_host.yml'

    - name: START | Install nginx
      include: '{{ tasks_base }}install.yml'

    - name: START | Execute status task
      include: '{{ common_tasks_base}}status.yml'

    - name: START | Execute stats task
      include: '{{ common_tasks_base}}stats.yml'
