---
- name: Create a '{{ container_name }}' container based on '{{ image }}'
  hosts: dockerhost
  gather_facts: no
  sudo: no

  vars:
    - do_debug: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

  tasks:
    - name: Check "{{ volume_home }}/plugins" folder
      file: dest="{{ volume_home }}/plugins" state=directory mode=0775
      register: checkout
      failed_when: checkout.state != "directory"
    - debug: msg="{{checkout}}"
      when: do_debug == True

    - name: Check "{{ volume_home }}/users" folder
      file: dest="{{ volume_home }}/users" state=directory mode=0775
      register: checkout
      failed_when: checkout.state != "directory"
    - debug: msg="{{checkout}}"
      when: do_debug == True

    - name: Check "{{ volume_home }}/jobs" folder
      file: dest="{{ volume_home }}/jobs" state=directory mode=0775
      register: checkout
      failed_when: checkout.state != "directory"
    - debug: msg="{{checkout}}"
      when: do_debug == True
