---
- name: Build {{ image }} image
  hosts: dockerhost
  sudo: False

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    # - include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check directory "{{ image_path }}" and create if not found
      file: dest={{ image_path }} state=directory
      register: checkout
      failed_when: checkout.state != 'directory'


    - name: Copy "{{ image }}" docker file to localhost
      synchronize:
        src: "{{ files_base }}/{{ image }}/"
        dest: "{{ image_path }}{{ image }}/"
        copy_links: yes

    - name: Check "{{ image }}" docker image folder
      stat: path="{{ image_path }}{{ image }}/"
      register: checkout
      failed_when: checkout.stat.exists == False

    - name: Check "{{ image }}/keys" folder
      file: dest="{{ image_path }}{{ image }}/keys" state=directory
      register: checkout
      failed_when: checkout.state != "directory"

    - name: Check "{{ image }}/etc" folder
      file: dest="{{ image_path }}{{ image }}/etc" state=directory
      register: checkout
      failed_when: checkout.state != "directory"


    - name: ensure private key file is protected
      file:
        path: "{{ local_base | realpath }}/files/keys/id_rsa"
        # path: "{{ image_path }}{{ image }}/keys/id_rsa"
        mode: 0600

    - name: copy private key file to destination
      copy:
        src: "{{ local_base | realpath }}/files/keys/id_rsa"
        dest: "{{ image_path }}{{ image }}/keys/id_rsa"
        mode: 0600

    - name: ensure public key file is protected
      file:
        path: "{{ local_base | realpath }}/files/keys/id_rsa.pub"
        # path: "{{ image_path }}{{ image }}/keys/id_rsa.pub"
        mode: 0600

    - name: copy public key file to destination
      copy:
        src: "{{ local_base | realpath }}/files/keys/id_rsa.pub"
        dest: "{{ image_path }}{{ image }}/keys/id_rsa.pub"
        mode: 0600


    - name: copy timezone file to destination
      copy:
        src: "{{ local_base | realpath }}/files/etc/timezone"
        dest: "{{ image_path }}{{ image }}/etc/timezone"
        mode: 0644

    - name: Create "{{ image }}" docker image
      # docker_image:
      #  name: base
      #  path: /home/homeboy/work/playbooks/local_test/files/docker/base
      #  state: build
      command: docker build -t {{ image }} "{{ image_path }}{{ image }}"
      register: buildout
      failed_when: buildout.rc != 0
