---
- name: Handle configs for an instance
  hosts: dockerhost
  sudo: False

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    # - debug: vars=ansible_env msg="{{ ansible_env }}"

    # - debug: vars=local_base msg="{{ local_base }}"

    # - debug: vars=config_base msg="{{ config_base }}"

    # - debug: vars=files_base msg="{{ files_base }}"

    # - debug: vars=tasks_base msg="{{ tasks_base }}"

    # - debug: vars=image msg="{{ image }}"

    # - debug: vars=env_name msg="{{ env_name }}"

    # - debug: msg="{{ lookup('pipe', 'ls -la ../../configs/.secrets/vpf.txt') }} is the raw result of running this command"

    - include: '{{ tasks_base }}check_connection.yml'

    - name: Create "{{ jenkins_base }}/{{ env_name }}" folder
      file: dest="{{ jenkins_base }}/{{ env_name }}" state=directory mode=0775
      register: checkout
      failed_when: checkout.state != "directory"
    # - debug: vars=checkout msg="{{checkout}}"

    - name: Create folders in "{{ jenkins_base }}/{{ env_name }}/users/" for default user configs
      file: dest="{{ jenkins_base }}/{{ env_name }}/users/{{ item | dirname | basename }}/" state=directory mode=0775
      #debug: vars="{{ item }}" msg="{{jenkins_base}}/{{ env_name }}/users/{{ item | dirname | basename }}/"
      register: checkout
      failed_when: checkout.state != "directory"
      with_fileglob:
        - "{{ files_base }}{{ image }}//jenkins/users/**/*.j2"

    - name: Create folders in "{{jenkins_base}}/{{ env_name }}/jobs/" for default job configs
      file: dest="{{ item | dirname | replace(files_base + image + "/jenkins", jenkins_base + "/" + env_name) }}/" state=directory mode=0775
      #debug: vars="{{ item }}" msg="{{ item | dirname | replace(files_base + image + "/jenkins", jenkins_base + "/" + env_name) }}/"
      register: checkout
      failed_when: checkout.state != "directory"
      with_fileglob:
        - "{{ files_base }}{{ image }}/jenkins/jobs/**/*.j2"
        - "{{ files_base }}{{ image }}/jenkins/jobs/**/jobs/**/*.j2"

  tasks:
    - name: Process template for configs
      template: src="{{ item }}" dest="{{jenkins_base}}/{{ env_name }}/{{ item | basename | regex_replace('^(.*)\.j2$', '\\1') }}"
      with_fileglob:
        - "{{ files_base }}{{ image }}/jenkins/*.j2"

    - name: Process templates for default user configs
      template: src="{{ item }}" dest="{{jenkins_base}}/{{ env_name }}/users/{{ item | dirname | basename }}/{{ item | basename | regex_replace('^(.*)\.j2$', '\\1') }}"
      #debug: vars="{{ item }}" msg="{{jenkins_base}}/{{ env_name }}/users/{{ item | dirname | basename }}/{{ item | basename | regex_replace('^(.*)\.j2$', '\\1') }}"
      with_fileglob:
        - "{{ files_base }}{{ image }}/jenkins/users/**/*.j2"

    - name: Process templates for default job configs
      template: src="{{ item }}" dest="{{ item | dirname | replace(files_base + image + "/jenkins", jenkins_base + "/" + env_name) }}/{{ item | basename | regex_replace('^(.*)\.j2$', '\\1') }}"
      #debug: vars="{{ item }}" msg="{{ item | dirname | replace(files_base + image + "/jenkins", jenkins_base + "/" + env_name) }}/{{ item | basename | regex_replace('^(.*)\.j2$', '\\1') }}"
      with_fileglob:
        - "{{ files_base }}{{ image }}/jenkins/jobs/**/*.j2"
        - "{{ files_base }}{{ image }}/jenkins/jobs/**/jobs/**/*.j2"

    - name: Copy credentials file
      copy: content="{{ lookup('pipe', 'ansible-vault view --vault-password-file=../../configs/.secrets/vpf.txt ' + files_base + image + '/jenkins/credentials.xml') }}" dest="{{ jenkins_base }}/{{ env_name }}/credentials.xml"
