---
- name: Create a new {{ env_name }} environment config based on .template.json.j2
  hosts: dockerhost
  sudo: False

  vars:
    - volume_home: ""

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    # - include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - debug: vars=image msg="{{ image }}"
      when: image is defined and image != ""

    - name: Process template to new environment of all images
      template: src="{{ item }}" dest="{{ item | dirname }}/{{ env_name }}.json"
      #debug: msg="{{ item | dirname }}/{{ env_name }}.json"
      with_fileglob:
        - "{{ config_base }}/**/.template.json.j2"
      when: image is defined and image == ""

    - name: Process template to new environment of specific image
      template: src="{{ item }}" dest="{{ item | dirname }}/{{ env_name }}.json"
      #debug: msg="{{ item | dirname }}/{{ env_name }}.json"
      with_fileglob:
        - "{{ config_base }}/{{ image }}/.template.json.j2"
      when: image is defined and image != ""

    - name: Create "{{ item }}" folder
      file: dest="{{ item }}" state=directory
      register: checkout
      failed_when: checkout.state != "directory"
      with_items:
      - "{{ jenkins_base }}/{{ env_name }}"
      - "{{ jenkins_data_base }}/{{ env_name }}"
      when: image is defined and image == ""
