---
- name: Create a new {{ env_name }} environment config based on .template.json.j2
  hosts: dockerhost
  sudo: False

  vars:
    - volume_home_check_disabled: true

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    # - include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

    - include: '{{ tasks_base }}check_folders.yml'

  tasks:
    - name: Process template to new environment
      template: src="{{ item }}" dest="{{ item | dirname }}/{{ env_name }}.json"
      with_fileglob:
        - "{{ config_base }}/**/.template.json.j2"

    - name: Create "{{ item }}" folder
      file: dest="{{ item }}" state=directory
      register: checkout
      failed_when: checkout.state != "directory"
      with_items:
      - "{{ jenkins_base }}/{{ env_name }}"
      - "{{ jenkins_data_base }}/{{ env_name }}"
