---
- name: Delete a {{ env_name }} environment config
  hosts: dockerhost
  sudo: False

  vars:
    - volume_home: ""
    - clean_up: False

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    # - include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - debug: vars=image msg="{{ image }}"
      when: image is defined and image != ""

    - name: Cleanup environment config files from all images
      file: dest="{{ item }}" state=absent
      #debug: msg="{{ item }}"
      register: checkout
      failed_when: checkout.state != "absent"
      with_fileglob:
        - "{{ config_base }}/**/{{ env_name }}.json"
      when: image is defined and image == ""

    - name: Cleanup environment config file from specific image
      file: dest="{{ item }}" state=absent
      #debug: msg="{{ item }}"
      register: checkout
      failed_when: checkout.state != "absent"
      with_fileglob:
        - "{{ config_base }}/{{ image }}/{{ env_name }}.json"
      when: image is defined and image != ""

    - debug: vars=clean_up msg="DELETE? {{ clean_up }}"
      when: clean_up|bool and image is defined

    - name: Delete "{{ item }}" folder
      file: dest="{{ item }}" state=absent
      register: checkout
      failed_when: checkout.state != "absent"
      with_items:
      - "{{ jenkins_base }}/{{ env_name }}"
      - "{{ jenkins_data_base }}/{{ env_name }}"
      when: clean_up|bool and image is defined and image == ""
