---
- name: Delete a {{ environment }} environment config
  hosts: dockerhost
  sudo: False

  vars:
    clean_up: False

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}check_connection.yml'

    # - debug: vars=ansible_env msg="{{ ansible_env }}"
    #
    # - debug: vars=local_base msg="{{ local_base | realpath }}"
    #
    # - debug: vars=config_base msg="{{ config_base }}"
    #
    # - debug: vars=env_name msg="{{ env_name }}"


    - name: Check directory {{ config_base }} and create if not found
      file: dest={{ config_base }} state=directory
      register: checkout

    - fail: msg="Create failed!"
      when: checkout.state != 'directory'

  tasks:
    - name: Cleanup environment config files
      file: dest="{{ item }}" state=absent
      with_fileglob:
        - "{{ config_base }}/**/{{ env_name }}.json"

    - name: Delete {{ jenkins_base }}/{{ env_name }} folder
      file: dest="{{ jenkins_base }}/{{ env_name }}" state=absent
      when: clean_up

    - name: Delete {{ jenkins_data_base }}/{{ env_name }} folder
      file: dest="{{ jenkins_data_base }}/{{ env_name }}" state=absent
      when: clean_up
