---
- name: Delete a {{ env_name }} environment config
  hosts: dockerhost
  sudo: False

  vars:
    clean_up: False

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    # - include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

    - include: '{{ tasks_base }}check_folders.yml'

  tasks:
    - name: Cleanup environment config files
      file: dest="{{ item }}" state=absent
      with_fileglob:
        - "{{ config_base }}/**/{{ env_name }}.json"

    - name: Delete "{{ item }}" folder
      file: dest="{{ item }}" state=absent
      register: checkout
      failed_when: checkout.state != "absent"
      when: clean_up
      with_items:
      - "{{ jenkins_base }}/{{ env_name }}"
      - "{{ jenkins_data_base }}/{{ env_name }}"
