---
- name: Stop a running '{{ container_name }}' container based on '{{ image }}' and delete
  hosts: dockerhost
  sudo: False

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  tasks:
    - include: '{{ tasks_base }}check_connection.yml'

    - include: '{{ tasks_base }}get_facts.yml'

    - include: '{{ tasks_base }}add_host.yml'

    - include: '{{ tasks_base }}stop.yml'

    - include: '{{ tasks_base }}remove.yml'
