---
- name: IMAGES | Execute docker image ls with an grep for name '{{ image }}'
  shell: docker image ls | grep '{{ image }}'
  when: image != ''
  register: checkout
  changed_when: checkout.rc != 0
  tags: human_log(stdout|stderr)
- debug: msg='IMAGES | {{ checkout }}'
  when: do_debug|bool and checkout is defined

- name: IMAGES | Execute docker image ls
  shell: docker image ls
  when: image == ''
  register: checkout
  changed_when: checkout.rc != 0
  tags: human_log(stdout|stderr)
- debug: msg='IMAGES | {{ checkout }}'
  when: do_debug|bool and checkout is defined
