---
- name: IMAGES | Execute docker images with an grep for name '{{ image }}'
  shell: docker images | grep '{{ image }}'
  when: image != ''
  register: checkout
  changed_when: checkout.rc != 0
  tags: human_log(stdout|stderr)
- debug: msg='IMAGES | {{ checkout }}'
  when: do_debug|bool and checkout is defined

- name: IMAGES | Execute docker images
  shell: docker images
  when: image == ''
  register: checkout
  changed_when: checkout.rc != 0
  tags: human_log(stdout|stderr)
- debug: msg='IMAGES | {{ checkout }}'
  when: do_debug|bool and checkout is defined
