---
- debug: msg='START | Use image "{{ image }}"'
  when: do_debug|bool
- debug: msg='START | Use container_name "{{ container_name }}"'
  when: do_debug|bool
- debug: msg='START | Use ports "{{ ports }}"'
  when: do_debug|bool
- debug: msg='START | Use volumes "{{ volumes }}"'
  when: do_debug|bool


- debug: msg='START | Use "standard" entrypoint.'
  when: do_debug|bool and not has_custom_command|bool
- name: START | Create client container '{{ container_name }}' with standard command
  docker_container:
    # api_version: 1.17
    image: '{{ image }}'
    name: '{{ container_name }}'
    hostname: '{{ container_name }}'
    exposed: '{{ ports }}'
    ports: '{{ ports }}'
    volumes: '{{ volumes }}'
    state: started
  register: checkout
  when: not has_custom_command|bool


- debug: msg='START | Use "{{ command }}" with custom entrypoint.'
  when: do_debug|bool and has_custom_command|bool
- name: START | Create client container '{{ container_name }}' with custom command
  docker_container:
    # api_version: 1.17
    image: '{{ image }}'
    name: '{{ container_name }}'
    hostname: '{{ container_name }}'
    exposed: '{{ ports }}'
    ports: '{{ ports }}'
    volumes: '{{ volumes }}'
    command: '{{ command }}'
    state: started
  register: checkout
  when: has_custom_command|bool


- debug: msg='START | {{ checkout }}'
  #when: do_debug|bool and not has_custom_command|bool
- debug: msg='START | {{ ansible_docker_container }}'
  #when: do_debug|bool and not has_custom_command|bool

# - fail: msg='[Error] START | Container '{{ container_name }}' with standard entrypoint is not running'
#   when: not has_custom_command|bool and checkout.changed|bool and checkout.summary.started == '1'
