---
- debug: msg='STATUS | {{ image }}_{{ app_name }}_{{ env_name }}'
  when: do_debug|bool and image != '' and app_name != '' and env_name != ''
- name: STATUS | Execute docker ps with an name '{{ image }}_{{ app_name }}_{{ env_name }}'
  shell: docker ps -a -f name='{{ image }}_{{ app_name }}_{{ env_name }}' | tail -n +2
  when: image != '' and app_name != '' and env_name != ''
  register: checkout
- debug: msg='STATUS | {{ checkout }}'
  when: do_debug|bool and checkout is defined
  
- debug: msg='STATUS | {{ image }}_{{ app_name }}'
  when: do_debug|bool and image != '' and app_name != '' and env_name == ''
- name: STATUS | Execute docker ps with an name '{{ image }}_{{ app_name }}'
  shell: docker ps -a -f name='{{ image }}_{{ app_name }}' | tail -n +2
  when: image != '' and app_name != '' and env_name == ''
  register: checkout
- debug: msg='STATUS | {{ checkout }}'
  when: do_debug|bool and checkout is defined
  
- debug: msg='STATUS | _{{ app_name }}'
  when: do_debug|bool and image == '' and app_name != '' and env_name == ''
- name: STATUS | Execute docker ps with an name '_{{ app_name }}'
  shell: docker ps -a -f name='_{{ app_name }}'
  when: image == '' and app_name != '' and env_name == ''
  register: checkout
- debug: msg='STATUS | {{ checkout }}'
  when: do_debug|bool and checkout is defined
  
- debug: msg='STATUS | {{ image }}_{{ env_name }}'
  when: do_debug|bool and image != '' and app_name == '' and env_name != ''
- name: STATUS | Execute docker ps with an name '{{ image }}_{{ env_name }}'
  shell: docker ps -a -f name='{{ image }}_{{ env_name }}' | tail -n +2
  when: image != '' and app_name == '' and env_name != ''
  register: checkout
- debug: msg='STATUS | {{ checkout }}'
  when: do_debug|bool and checkout is defined
  
- debug: msg='STATUS | _{{ env_name }}'
  when: do_debug|bool and image == '' and app_name == '' and env_name != ''
- name: STATUS | Execute docker ps with an name '_{{ env_name }}'
  shell: docker ps -a -f name='_{{ env_name }}'
  when: image == '' and app_name == '' and env_name != ''
  register: checkout
- debug: msg='STATUS | {{ checkout }}'
  when: do_debug|bool and checkout is defined
  
- debug: msg='STATUS | {{ image }}'
  when: do_debug|bool and image == '' and app_name == '' and env_name == ''
- name: STATUS | Execute docker status with an name '{{ image }}' 
  shell: docker ps -a -f name='{{ image }}' | tail -n +2
  when: image != '' and app_name == '' and env_name == ''
  register: checkout
  changed_when: checkout.rc != 0
- debug: msg='STATUS | {{ checkout }}'
  when: do_debug|bool and checkout is defined

- debug: msg='STATUS | Normal docker ps'
  when: do_debug|bool and image == '' and app_name == '' and env_name == ''
- name: STATUS | Execute docker ps
  shell: docker ps -a
  when: image == '' and app_name == '' and env_name == '''
  register: checkout
- debug: msg='STATUS | {{ checkout }}'
  when: do_debug|bool and checkout is defined
