---
- name: BOOT | Create and start a running '{{ container_name }}' container based on '{{ image }}'
  hosts: dockerhost
  gather_facts: no
  sudo: no

  vars:
    - do_debug: False
    - do_check_docker: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - "{{ base_folder }}/roles/common/vars/defaults.yml"
    - "{{ base_folder }}/roles/{{ image }}/vars/defaults.yml"

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

    - include: '{{ common_tasks_base }}check_docker.yml'
      when: do_check_docker|bool

  tasks:
    - name: BOOT | Start docker container
      include: '{{ tasks_base }}start.yml'

    - name: BOOT | Get docker container information
      include: '{{ tasks_base }}get_facts.yml'

    - name: BOOT | Add docker container to inventory
      include: '{{ tasks_base }}add_host.yml'

    - name: BOOT | Execute status task
      include: "{{ common_tasks_base }}status.yml"

    - name: BOOT | Execute stats task
      include: "{{ common_tasks_base }}stats.yml"

#    - name: Output
#      debug: msg="[echo] {{ hostvars[container_name].ansible_ssh_host }}"
