---
- name: BOOT | Create and start a running {{ container_name }} container based on {{ image }}
  hosts: dockerhost
  hosts: "{{ host }}"
  gather_facts: no
  sudo: no

  vars:
    - do_debug: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - "{{ base_folder }}/roles/common/vars/defaults.yml"
    - "{{ base_folder }}/roles/site/vars/defaults.yml"

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

  tasks:
    - name: BOOT | Start docker container
      include: '{{ tasks_base }}start.yml'

    - name: BOOT | Get docker container information
      include: '{{ tasks_base }}get_facts.yml'

    - name: BOOT | Add docker container to inventory
      include: '{{ tasks_base }}add_host.yml'

#    - name: ping '{{ container_name }}'
#      shell: ping -c 1 "{{ hostvars[container_name].ansible_ssh_host }}"
      # ping:
      # shell: ping -c 1 "{{ item.value.docker_networksettings.IPAddress }}"
      # when: item.value.docker_state.Running == True
      # with_dict: docker_containers
#      register: output

#    - name: Output
#      debug: msg="[echo] {{ output.rc }}"
#      # debug: msg="[echo] {{ output.results[0].rc }}"
#    - name: Output
#      debug: msg="[echo] {{ hostvars[container_name].ansible_ssh_host }}"
