---
- name: DELETE | Delete a '{{ env_name }}' environment config
  hosts: dockerhost
  gather_facts: no
  sudo: no

  vars:
    - do_debug: False
    - do_check_connection: False
    - base_folder: ..
    - clean_up: False

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'
    - '{{ base_folder }}/roles/{{ image }}/vars/defaults.yml'

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

  tasks:
    - name: DELETE | Delete docker environment
      include: '{{ tasks_base }}delete.yml'
