---
- name: Destroys a local image from local docker repository
  hosts: dockerhost
  sudo: False

  vars:
    - do_debug: False

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug == True
    
    - name: Execute docker rmi with an name "{{ image }}" 
      shell: docker rmi "{{ image }}" | tail -n +2
      when: "'{{ image }}' != ''"
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug == True
