---
- name: FETCH | Fetch standard images from docker hub
  hosts: dockerhost
  gather_facts: no
  become: no

  vars:
    - do_debug: False
    - do_check_docker: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include: '{{ common_tasks_base }}check_docker.yml'
      when: do_check_docker|bool

  tasks:
    - name: FETCH | Execute fetch task for '{{ inventory_hostname }}'
      include: '{{ common_tasks_base }}fetch.yml'
      tags: human_log(stdout|stderr)
