---
- name: List images on dockerhost
  hosts: dockerhost
  sudo: False

  vars:
    - volume_home: ""
    - image: ""
    - env_name: ""

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    #- include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check if "docker.io" is present
      apt:
        name: docker.io
        state: present
    #   register: checkout
    # - debug: msg="{{ checkout }}"
    
    - name: Execute docker images
      command: docker images
    #   register: output
      
    # - debug: msg="{{ output }}"