---
- name: List images on dockerhost
  hosts: dockerhost
  sudo: False

  vars:
    - do_debug: False

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug == True
    
    - name: Execute docker images with an grep for name "{{ image }}"
      shell: docker images | grep "{{ image }}"
      when: "'{{ image }}' != ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
    
    - name: Execute docker images
      shell: docker images
      when: "'{{ image }}' == ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
    
    - name: Execute docker status with an name "{{ image }}" 
      shell: docker ps -a -f name="{{ image }}" | tail -n +2
      when: "'{{ image }}' != ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
       
    - name: Execute docker status with an name "{{ image }}_{{ env_name }}"
      shell: docker ps -a -f name="{{ image }}_{{ env_name }}" | tail -n +2
      when: "'{{ image }}' != '' and '{{ env_name }}' != ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
       
    - name: Execute docker status
      shell: docker ps -a
      when: "'{{ image }}' == '' and '{{ env_name }}' == ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
