---
- name: REMOVE IMAGE | Destroys a local image '{{ image }}' from local docker repository
  hosts: dockerhost
  gather_facts: no
  become: no

  vars:
    - do_debug: False
    - do_check_docker: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'
    - '{{ base_folder }}/roles/{{ image }}/vars/defaults.yml'

  pre_tasks:
    - include_tasks: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include_tasks: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include_tasks: '{{ common_tasks_base }}check_docker.yml'
      when: do_check_docker|bool

  tasks:
    - name: REMOVE IMAGE | Execute stats task
      include_tasks: '{{ tasks_base }}removeimage.yml'
