---
- name: Remove image based on '{{ image }}'
  hosts: dockerhost
  sudo: False

  vars_files:
    - ../../roles/dockerhost/vars/base.yml

  pre_tasks:
    # - include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - include: '{{ tasks_base }}removeimage.yml'
