---
- name: Remove image based on {{ image }}
  hosts: dockerhost
  sudo: False

  vars:
    - do_debug: False

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - include: '{{ tasks_base }}removeimage.yml'
