---
- name: SETUP | Create a '{{ container_name }}' container based on '{{ image }}'
  hosts: dockerhost
  gather_facts: no
  become: no

  vars:
    - do_debug: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'
    - '{{ base_folder }}/roles/{{ image }}/vars/defaults.yml'

  pre_tasks:
    - include_tasks: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include_tasks: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include_tasks: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

  tasks:
    - name: SETUP | Execute Setup task
      include_tasks: '{{ common_tasks_base }}setup.yml'
