---
- name: Create a {{ container_name }} container based on {{ image }}
  hosts: dockerhost
  sudo: False

  vars:
    - do_debug: False

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

    - include: '{{ tasks_base }}check_folders.yml'

  tasks:
    - name: Check "{{ volume_home }}/plugins" folder
      file: dest="{{ volume_home }}/plugins" state=directory mode=0775
      register: checkout
      failed_when: checkout.state != "directory"
    - debug: msg="{{checkout}}"
      when: do_debug == True

    - name: Check "{{ volume_home }}/users" folder
      file: dest="{{ volume_home }}/users" state=directory mode=0775
      register: checkout
      failed_when: checkout.state != "directory"
    - debug: msg="{{checkout}}"
      when: do_debug == True

    - name: Check "{{ volume_home }}/jobs" folder
      file: dest="{{ volume_home }}/jobs" state=directory mode=0775
      register: checkout
      failed_when: checkout.state != "directory"
    - debug: msg="{{checkout}}"
      when: do_debug == True
