---
- name: Stop a running {{ container_name }} container based on {{ image }}
  hosts: dockerhost
  sudo: False

  vars:
    - do_debug: False

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

    - include: '{{ tasks_base }}check_folders.yml'
      when: do_debug == True

  tasks:
    - include: '{{ tasks_base }}get_facts.yml'

    - include: '{{ tasks_base }}add_host.yml'

    - include: '{{ tasks_base }}stop.yml'
