---
- name: List images on dockerhost
  hosts: dockerhost
  sudo: False

  vars:
    - volume_home: ""
    - image: ""
    - env_name: ""

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
    #   register: checkout
    # - debug: msg="{{ checkout }}"
    
    - name: Execute docker status with an name "{{ image }}" 
      command: docker ps -a -f name="{{ image }}" | tail -n +2
      when: "'{{ image }}' != ''"
    #   register: output
    # - debug: msg="{{ output }}"
       
    - name: Execute docker status with an name "{{ image }}_{{ env_name }}"
      command: docker ps -a -f name="{{ image }}_{{ env_name }}" | tail -n +2
      when: "'{{ image }}' != '' and '{{ env_name }}' != ''"
    #   register: output
    # - debug: msg="{{ output }}"
       
    - name: Execute docker status
      command: docker ps -a
      when: "'{{ image }}' == '' and '{{ env_name }}' == ''"
    #   register: output
    # - debug: msg="{{ output }}"
