---
- name: STATS | List containers statistics on dockerhost
  hosts: dockerhost
  gather_facts: no
  sudo: no

  vars:
    - do_debug: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - "{{ base_folder }}/roles/common/vars/defaults.yml"
    - "{{ base_folder }}/roles/site/vars/defaults.yml"

  pre_tasks:
    - include: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

  tasks:
    - name: STATS | Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug|bool
    
    - debug: msg="{{ image }}_{{ app_name }}"
      when: do_debug|bool and '{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''
    - name: STATS | Execute docker logs with an name "{{ image }}_{{ app_name }}" 
      shell: docker logs --tail="30" "{{ image }}_{{ app_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''"
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug|bool
    
    - debug: msg="{{ image }}_{{ env_name }}"
      when: do_debug|bool and '{{ image }}' != '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''
    - name: STATS | Execute docker logs with an name "{{ image }}_{{ env_name }}" 
      shell: docker logs --tail="30" "{{ image }}_{{ env_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''"
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug|bool
    
    - debug: msg="{{ image }}_{{ app_name }}_{{ env_name }}"
      when: do_debug|bool and '{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' != ''
    - name: STATS | Execute docker logs with an name "{{ image }}_{{ app_name }}_{{ env_name }}" 
      shell: docker logs --tail="30" "{{ image }}_{{ app_name }}_{{ env_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' != ''"
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug|bool
