---
- name: STATUS | List status of container(s) on docker host
  hosts: dockerhost
  gather_facts: no
  become: no

  vars:
    - do_debug: False
    - do_check_docker: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'

  pre_tasks:
    - include_tasks: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include_tasks: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include_tasks: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

    - include_tasks: '{{ common_tasks_base }}check_docker.yml'
      when: do_check_docker|bool

  tasks:
    - name: STATUS | Execute status task on '{{ inventory_host }}'
      include_tasks: '{{ common_tasks_base}}status.yml'
