---
- name: List container(s) on dockerhost
  hosts: dockerhost
  sudo: False

  vars:
    - do_debug: True

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug == True
       
    - debug: msg="{{ image }}_{{ app_name }}_{{ env_name }}"
      when: do_debug == True and '{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' != ''
    - name: Execute docker ps with an name "{{ image }}_{{ app_name }}_{{ env_name }}"
      shell: docker ps -a -f name="{{ image }}_{{ app_name }}_{{ env_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' != ''"
       
    - debug: msg="{{ image }}_{{ app_name }}"
      when: do_debug == True and '{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''
    - name: Execute docker ps with an name "{{ image }}_{{ app_name }}"
      shell: docker ps -a -f name="{{ image }}_{{ app_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''"
       
    - debug: msg="_{{ app_name }}"
      when: do_debug == True and '{{ image }}' == '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''
    - name: Execute docker ps with an name "_{{ app_name }}"
      shell: docker ps -a -f name="_{{ app_name }}"
      when: "'{{ image }}' == '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''"
       
    - debug: msg="{{ image }}_{{ env_name }}"
      when: do_debug == True and '{{ image }}' != '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''
    - name: Execute docker ps with an name "{{ image }}_{{ env_name }}"
      shell: docker ps -a -f name="{{ image }}_{{ env_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''"
       
    - debug: msg="_{{ env_name }}"
      when: do_debug == True and '{{ image }}' == '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''
    - name: Execute docker ps with an name "_{{ env_name }}"
      shell: docker ps -a -f name="_{{ env_name }}"
      when: "'{{ image }}' == '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''"
       
    - debug: msg="Normal docker ps"
      when: do_debug == True and '{{ image }}' == '' and '{{ app_name }}' == '' and '{{ env_name }}' == ''
    - name: Execute docker ps
      shell: docker ps -a
      when: "'{{ image }}' == '' and '{{ app_name }}' == '' and '{{ env_name }}' == ''"
