---
- name: List containers statistics on dockerhost
  hosts: dockerhost
  sudo: False

  vars:
    - volume_home: ""
    - image: ""
    - app_name: ""
    - env_name: ""
    - do_debug: False

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug == True
    
    - debug: msg="{{ image }}_{{ app_name }}"
      when: do_debug == True and '{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''
    - name: Execute docker logs with an name "{{ image }}_{{ app_name }}" 
      shell: docker logs --tail="30" "{{ image }}_{{ app_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' == ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
    
    - debug: msg="{{ image }}_{{ env_name }}"
      when: do_debug == True and '{{ image }}' != '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''
    - name: Execute docker logs with an name "{{ image }}_{{ env_name }}" 
      shell: docker logs --tail="30" "{{ image }}_{{ env_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' == '' and '{{ env_name }}' != ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
    
    - debug: msg="{{ image }}_{{ app_name }}_{{ env_name }}"
      when: do_debug == True and '{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' != ''
    - name: Execute docker logs with an name "{{ image }}_{{ app_name }}_{{ env_name }}" 
      shell: docker logs --tail="30" "{{ image }}_{{ app_name }}_{{ env_name }}"
      when: "'{{ image }}' != '' and '{{ app_name }}' != '' and '{{ env_name }}' != ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
