---
- name: STOP | Stop a running '{{ container_name }}' container based on '{{ image }}'
  hosts: dockerhost
  gather_facts: no
  become: no

  vars:
    - do_debug: False
    - do_check_docker: False
    - do_check_folders: False
    - do_check_connection: False
    - base_folder: ..

  vars_files:
    - '{{ base_folder }}/roles/common/vars/defaults.yml'
    - '{{ base_folder }}/roles/{{ image }}/vars/defaults.yml'

  pre_tasks:
    - include_tasks: '{{ common_tasks_base }}/debug.yml'
      when: do_debug|bool

    - include_tasks: '{{ common_tasks_base }}check_connection.yml'
      when: do_check_connection|bool

    - include_tasks: '{{ common_tasks_base }}check_folders.yml'
      when: do_check_folders|bool

    - include_tasks: '{{ common_tasks_base }}check_docker.yml'
      when: do_check_docker|bool

  tasks:
    - name: STOP | Execute stats task
      include_tasks: '{{ common_tasks_base }}stats.yml'

    - name: STOP | Get docker container information
      include_tasks: '{{ common_tasks_base }}get_facts.yml'

    - name: STOP | Add docker container to inventory
      include_tasks: '{{ common_tasks_base }}add_host.yml'

    - name: STOP | Stop docker container
      include_tasks: '{{ common_tasks_base }}stop.yml'

    - name: STOP | Execute status task
      include_tasks: '{{ common_tasks_base }}status.yml'
