---
- name: Destroys all local running containers from local docker host '{{ container_host }}'
  hosts: dockerhost
  sudo: False

  vars:
    - do_debug: False

  vars_files:
    - ../roles/vars/base.yml

  pre_tasks:
    - include: '{{ tasks_base }}debug_info.yml'
      when: do_debug == True

    - include: '{{ tasks_base }}check_connection.yml'

  tasks:
    - name: Check if "docker.io" is present
      shell: dpkg-query --list docker.io    
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug == True
    
    - name: Execute docker stop and rm 
      shell: for j in $(docker ps -a -q); do echo Removing $j; echo docker stop $j; echo docker rm $j; echo; done
      register: checkout
    - debug: msg="{{ checkout }}"
      when: do_debug == True
       
    - name: Execute docker status
      shell: docker ps -a
      when: "'{{ image }}' == '' and '{{ env_name }}' == ''"
      register: output
    - debug: msg="{{ output }}"
      when: do_debug == True
